In [1]:
import pandas as pd
fake_df=pd.read_csv("Fake.csv")
real_df=pd.read_csv("True.csv")
fake_df.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [2]:
fake_df["label"]=0
real_df["label"]=1
fake_df.head()

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0

In [3]:
df=pd.concat([fake_df,real_df], axis=0)
df=df.sample(frac=1).reset_index(drop=True)
df.head()

,title,text,subject,date,label
0,FLASHBACK: ‘The Syrian War: What You’re Not Be...,"21st Century Wire says Back in August 2013, Un...",US_News,"December 18, 2016",0
1,NEW YORK TIMES Publishes FAKE Story About Dona...,Here s how fake news works In an effort to cas...,politics,"Jul 10, 2017",0
2,BREAKING: PROTESTER JUMPS ON STAGE…Grabs Trump...,A protester tried to attack Trump today at a r...,politics,"Mar 12, 2016",0
3,Senate Republican tax chief wants dividend ded...,WASHINGTON (Reuters) - The U.S. Senate’s top R...,politicsNews,"September 19, 2017",1
4,WATCH: Bill O’Reilly Just Said The Women’s Ma...,Bill O Reilly can always be trusted to be a to...,News,"January 23, 2017",0

In [4]:
df.shape

(44898, 5)

In [5]:
df.head()

,title,text,subject,date,label
0,FLASHBACK: ‘The Syrian War: What You’re Not Be...,"21st Century Wire says Back in August 2013, Un...",US_News,"December 18, 2016",0
1,NEW YORK TIMES Publishes FAKE Story About Dona...,Here s how fake news works In an effort to cas...,politics,"Jul 10, 2017",0
2,BREAKING: PROTESTER JUMPS ON STAGE…Grabs Trump...,A protester tried to attack Trump today at a r...,politics,"Mar 12, 2016",0
3,Senate Republican tax chief wants dividend ded...,WASHINGTON (Reuters) - The U.S. Senate’s top R...,politicsNews,"September 19, 2017",1
4,WATCH: Bill O’Reilly Just Said The Women’s Ma...,Bill O Reilly can always be trusted to be a to...,News,"January 23, 2017",0

In [6]:
df.isnull().sum()

title      0
text       0
subject    0
date       0
label      0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(209)

In [8]:
df.drop_duplicates(inplace=True)
df.shape

(44689, 5)

In [9]:
#Uppercase to Lowercase
df["text"]=df["text"].str.lower()
# to see one row
df["text"].iloc[0]

'21st century wire says back in august 2013, united nations investigators led by carla del ponte found evidence that alleged chemical weapons attacks by the syrian military were actually staged by us, saudi and qatari-backed jihadist  rebels.  by definition, this was a false flag attack. regardless of the facts, western media and political leaders still decided to blame damascus for the incident. the object of this game was simple: to engineer a virtual  violation  of obama s famous red line, providing the legal pretext, however spurious, for the use of western military force against the nation state of syria   under the guise of the great 21st century western military intervention tactic known as the  responsibility to protect  (r2p). this video was uploaded by storm clouds gathering on sept 3, 2013, and it demonstrated how when the entire mainstream media is going one way   pushing a fraudulent event for the purposes of generating a new war   alternative media outlets were reporting the truth. history is on the side of alternative media, not for the likes of cnn, abc, nbc, bbc and al jazeera. that was the week when everyone in the west thought that the us-led military action against syria was a fait accompli. thanks to a brief wave of sanity which swept through the british parliament, the us could not proceed forward without appearing  hilteresque themselves. despite all the hype and all the mainstream media fake news, washington and london s official conspiracy theory was that assad crossed a red line by using sarin gas against his own people. here is a timely analysis, one with a wider geopolitical scope, delivered by aaron hawkins founder of storm clouds gathering. watch: support 21wire  subscribe & become a member @ 21wire.tv'

In [10]:
#removing urls using regex
import re
def remove_urls(text):
  return re.sub(r"http\S+|www\S+","",text)
df["text"] =df["text"].apply(remove_urls)
df["text"].iloc[0]

'21st century wire says back in august 2013, united nations investigators led by carla del ponte found evidence that alleged chemical weapons attacks by the syrian military were actually staged by us, saudi and qatari-backed jihadist  rebels.  by definition, this was a false flag attack. regardless of the facts, western media and political leaders still decided to blame damascus for the incident. the object of this game was simple: to engineer a virtual  violation  of obama s famous red line, providing the legal pretext, however spurious, for the use of western military force against the nation state of syria   under the guise of the great 21st century western military intervention tactic known as the  responsibility to protect  (r2p). this video was uploaded by storm clouds gathering on sept 3, 2013, and it demonstrated how when the entire mainstream media is going one way   pushing a fraudulent event for the purposes of generating a new war   alternative media outlets were reporting the truth. history is on the side of alternative media, not for the likes of cnn, abc, nbc, bbc and al jazeera. that was the week when everyone in the west thought that the us-led military action against syria was a fait accompli. thanks to a brief wave of sanity which swept through the british parliament, the us could not proceed forward without appearing  hilteresque themselves. despite all the hype and all the mainstream media fake news, washington and london s official conspiracy theory was that assad crossed a red line by using sarin gas against his own people. here is a timely analysis, one with a wider geopolitical scope, delivered by aaron hawkins founder of storm clouds gathering. watch: support 21wire  subscribe & become a member @ 21wire.tv'

In [11]:
#Removing html tags
def remove_html_tags(text):
  return re.sub(r"<.*?>","",text)
df["text"]=df["text"].apply(remove_html_tags)
df["text"].iloc[0]

'21st century wire says back in august 2013, united nations investigators led by carla del ponte found evidence that alleged chemical weapons attacks by the syrian military were actually staged by us, saudi and qatari-backed jihadist  rebels.  by definition, this was a false flag attack. regardless of the facts, western media and political leaders still decided to blame damascus for the incident. the object of this game was simple: to engineer a virtual  violation  of obama s famous red line, providing the legal pretext, however spurious, for the use of western military force against the nation state of syria   under the guise of the great 21st century western military intervention tactic known as the  responsibility to protect  (r2p). this video was uploaded by storm clouds gathering on sept 3, 2013, and it demonstrated how when the entire mainstream media is going one way   pushing a fraudulent event for the purposes of generating a new war   alternative media outlets were reporting the truth. history is on the side of alternative media, not for the likes of cnn, abc, nbc, bbc and al jazeera. that was the week when everyone in the west thought that the us-led military action against syria was a fait accompli. thanks to a brief wave of sanity which swept through the british parliament, the us could not proceed forward without appearing  hilteresque themselves. despite all the hype and all the mainstream media fake news, washington and london s official conspiracy theory was that assad crossed a red line by using sarin gas against his own people. here is a timely analysis, one with a wider geopolitical scope, delivered by aaron hawkins founder of storm clouds gathering. watch: support 21wire  subscribe & become a member @ 21wire.tv'

In [12]:
# emoji removal
def remove_emojis(text):
    # this pattern defines RANGES of unicode characters that represent emojis
    # unicode is just a big numbered list where every character (letters, symbols, emojis) has a unique number
    # emojis live in specific number ranges, so we can target just those ranges
    emoji_pattern = re.compile(
        "["
        "\U0001F600-\U0001F64F"  # emoticons (like 😀 😂 😭)
        "\U0001F300-\U0001F5FF"  # symbols & pictographs (like 🔥 💀)
        "\U0001F680-\U0001F6FF"  # transport & map symbols
        "\U0001F1E0-\U0001F1FF"  # flags
        "]+", flags=re.UNICODE
    )
    return emoji_pattern.sub("", text)

df["text"] = df["text"].apply(remove_emojis)

# check again
df["text"].iloc[0]
# not used this function

'washington (reuters) - u.s. republican presidential candidate ted cruz’s campaign is vetting former business executive carly fiorina as a possible vice presidential pick, abc news said on friday. earlier, cruz’s campaign said it had narrowed its running mate options to a short list. fiorina, a former ceo of hewlett packard, dropped out of the presidential race in february. '

In [12]:
def remove_punctuation(text):
    # [^a-z0-9\s] ka matlab: "koi bhi character jo a-z, 0-9, ya space NA ho"
    # ^ (caret) andar hone ka matlab hai "NOT" - yaani in teeno ke alawa sab kuch
    # aisa har character space se replace ho jaayega
    text = re.sub(r'[^a-z0-9\s]', ' ', text)

    # multiple spaces ko single space mein convert karo
    text = re.sub(r'\s+', ' ', text).strip()

    return text

In [13]:
#Removing numbers
def remove_numbers(text):
  return re.sub(r"\d+","",text)
df["text"]=df["text"].apply(remove_numbers)
df["text"].iloc[0]

'st century wire says back in august , united nations investigators led by carla del ponte found evidence that alleged chemical weapons attacks by the syrian military were actually staged by us, saudi and qatari-backed jihadist  rebels.  by definition, this was a false flag attack. regardless of the facts, western media and political leaders still decided to blame damascus for the incident. the object of this game was simple: to engineer a virtual  violation  of obama s famous red line, providing the legal pretext, however spurious, for the use of western military force against the nation state of syria   under the guise of the great st century western military intervention tactic known as the  responsibility to protect  (rp). this video was uploaded by storm clouds gathering on sept , , and it demonstrated how when the entire mainstream media is going one way   pushing a fraudulent event for the purposes of generating a new war   alternative media outlets were reporting the truth. history is on the side of alternative media, not for the likes of cnn, abc, nbc, bbc and al jazeera. that was the week when everyone in the west thought that the us-led military action against syria was a fait accompli. thanks to a brief wave of sanity which swept through the british parliament, the us could not proceed forward without appearing  hilteresque themselves. despite all the hype and all the mainstream media fake news, washington and london s official conspiracy theory was that assad crossed a red line by using sarin gas against his own people. here is a timely analysis, one with a wider geopolitical scope, delivered by aaron hawkins founder of storm clouds gathering. watch: support wire  subscribe & become a member @ wire.tv'

In [14]:
# Removing stopwords
import nltk #natural language tootkit,a library
from nltk.corpus import stopwords
nltk.download('stopwords')
stop_words=set(stopwords.words('english'))
def remove_stopwords(text):
  words=text.split()
  filtered_words=[word for word in words if word not in stop_words]
  return " ".join(filtered_words)
df["text"]=df["text"].apply(remove_stopwords)
df["text"].iloc[0]

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

'st century wire says back august , united nations investigators led carla del ponte found evidence alleged chemical weapons attacks syrian military actually staged us, saudi qatari-backed jihadist rebels. definition, false flag attack. regardless facts, western media political leaders still decided blame damascus incident. object game simple: engineer virtual violation obama famous red line, providing legal pretext, however spurious, use western military force nation state syria guise great st century western military intervention tactic known responsibility protect (rp). video uploaded storm clouds gathering sept , , demonstrated entire mainstream media going one way pushing fraudulent event purposes generating new war alternative media outlets reporting truth. history side alternative media, likes cnn, abc, nbc, bbc al jazeera. week everyone west thought us-led military action syria fait accompli. thanks brief wave sanity swept british parliament, us could proceed forward without appearing hilteresque themselves. despite hype mainstream media fake news, washington london official conspiracy theory assad crossed red line using sarin gas people. timely analysis, one wider geopolitical scope, delivered aaron hawkins founder storm clouds gathering. watch: support wire subscribe & become member @ wire.tv'

In [15]:
#tokenization
from nltk.tokenize import word_tokenize
nltk.download('punkt') #punkt pretrained model to seperate words corectly
def tokenize_text(text):
  return word_tokenize(text)
df["tokens"]=df["text"].apply(tokenize_text)
df["tokens"].iloc[0]

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

['st',
 'century',
 'wire',
 'says',
 'back',
 'august',
 ',',
 'united',
 'nations',
 'investigators',
 'led',
 'carla',
 'del',
 'ponte',
 'found',
 'evidence',
 'alleged',
 'chemical',
 'weapons',
 'attacks',
 'syrian',
 'military',
 'actually',
 'staged',
 'us',
 ',',
 'saudi',
 'qatari-backed',
 'jihadist',
 'rebels',
 '.',
 'definition',
 ',',
 'false',
 'flag',
 'attack',
 '.',
 'regardless',
 'facts',
 ',',
 'western',
 'media',
 'political',
 'leaders',
 'still',
 'decided',
 'blame',
 'damascus',
 'incident',
 '.',
 'object',
 'game',
 'simple',
 ':',
 'engineer',
 'virtual',
 'violation',
 'obama',
 'famous',
 'red',
 'line',
 ',',
 'providing',
 'legal',
 'pretext',
 ',',
 'however',
 'spurious',
 ',',
 'use',
 'western',
 'military',
 'force',
 'nation',
 'state',
 'syria',
 'guise',
 'great',
 'st',
 'century',
 'western',
 'military',
 'intervention',
 'tactic',
 'known',
 'responsibility',
 'protect',
 '(',
 'rp',
 ')',
 '.',
 'video',
 'uploaded',
 'storm',
 'clouds',
 'gathering',
 'sept',
 ',',
 ',',
 'demonstrated',
 'entire',
 'mainstream',
 'media',
 'going',
 'one',
 'way',
 'pushing',
 'fraudulent',
 'event',
 'purposes',
 'generating',
 'new',
 'war',
 'alternative',
 'media',
 'outlets',
 'reporting',
 'truth',
 '.',
 'history',
 'side',
 'alternative',
 'media',
 ',',
 'likes',
 'cnn',
 ',',
 'abc',
 ',',
 'nbc',
 ',',
 'bbc',
 'al',
 'jazeera',
 '.',
 'week',
 'everyone',
 'west',
 'thought',
 'us-led',
 'military',
 'action',
 'syria',
 'fait',
 'accompli',
 '.',
 'thanks',
 'brief',
 'wave',
 'sanity',
 'swept',
 'british',
 'parliament',
 ',',
 'us',
 'could',
 'proceed',
 'forward',
 'without',
 'appearing',
 'hilteresque',
 'themselves',
 '.',
 'despite',
 'hype',
 'mainstream',
 'media',
 'fake',
 'news',
 ',',
 'washington',
 'london',
 'official',
 'conspiracy',
 'theory',
 'assad',
 'crossed',
 'red',
 'line',
 'using',
 'sarin',
 'gas',
 'people',
 '.',
 'timely',
 'analysis',
 ',',
 'one',
 'wider',
 'geopolitical',
 'scope',
 ',',
 'delivered',
 'aaron',
 'hawkins',
 'founder',
 'storm',
 'clouds',
 'gathering',
 '.',
 'watch',
 ':',
 'support',
 'wire',
 'subscribe',
 '&',
 'become',
 'member',
 '@',
 'wire.tv']

In [21]:
#lookup error fixed
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')  # newer nltk versions need this additional resource for tokenization

from nltk.tokenize import word_tokenize

def tokenize_text(text):
    return word_tokenize(text)

df["tokens"] = df["text"].apply(tokenize_text)
df["tokens"].iloc[0]

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

['washington',
 '(',
 'reuters',
 ')',
 '-',
 'u.s.',
 'republican',
 'presidential',
 'candidate',
 'ted',
 'cruz',
 '’',
 's',
 'campaign',
 'vetting',
 'former',
 'business',
 'executive',
 'carly',
 'fiorina',
 'possible',
 'vice',
 'presidential',
 'pick',
 ',',
 'abc',
 'news',
 'said',
 'friday',
 '.',
 'earlier',
 ',',
 'cruz',
 '’',
 's',
 'campaign',
 'said',
 'narrowed',
 'running',
 'mate',
 'options',
 'short',
 'list',
 '.',
 'fiorina',
 ',',
 'former',
 'ceo',
 'hewlett',
 'packard',
 ',',
 'dropped',
 'presidential',
 'race',
 'february',
 '.']

In [16]:
#lemmatization
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')  # wordnet ek dictionary-type database hai jo lemmatizer use karta hai root words dhundhne ke liye

lemmatizer = WordNetLemmatizer()

def lemmatize_tokens(tokens):
    # har token (word) ko uske root form mein convert karte hain
    return [lemmatizer.lemmatize(word) for word in tokens]

df["tokens"] = df["tokens"].apply(lemmatize_tokens)

# check karte hain ek example
df["tokens"].iloc[0]

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

['st',
 'century',
 'wire',
 'say',
 'back',
 'august',
 ',',
 'united',
 'nation',
 'investigator',
 'led',
 'carla',
 'del',
 'ponte',
 'found',
 'evidence',
 'alleged',
 'chemical',
 'weapon',
 'attack',
 'syrian',
 'military',
 'actually',
 'staged',
 'u',
 ',',
 'saudi',
 'qatari-backed',
 'jihadist',
 'rebel',
 '.',
 'definition',
 ',',
 'false',
 'flag',
 'attack',
 '.',
 'regardless',
 'fact',
 ',',
 'western',
 'medium',
 'political',
 'leader',
 'still',
 'decided',
 'blame',
 'damascus',
 'incident',
 '.',
 'object',
 'game',
 'simple',
 ':',
 'engineer',
 'virtual',
 'violation',
 'obama',
 'famous',
 'red',
 'line',
 ',',
 'providing',
 'legal',
 'pretext',
 ',',
 'however',
 'spurious',
 ',',
 'use',
 'western',
 'military',
 'force',
 'nation',
 'state',
 'syria',
 'guise',
 'great',
 'st',
 'century',
 'western',
 'military',
 'intervention',
 'tactic',
 'known',
 'responsibility',
 'protect',
 '(',
 'rp',
 ')',
 '.',
 'video',
 'uploaded',
 'storm',
 'cloud',
 'gathering',
 'sept',
 ',',
 ',',
 'demonstrated',
 'entire',
 'mainstream',
 'medium',
 'going',
 'one',
 'way',
 'pushing',
 'fraudulent',
 'event',
 'purpose',
 'generating',
 'new',
 'war',
 'alternative',
 'medium',
 'outlet',
 'reporting',
 'truth',
 '.',
 'history',
 'side',
 'alternative',
 'medium',
 ',',
 'like',
 'cnn',
 ',',
 'abc',
 ',',
 'nbc',
 ',',
 'bbc',
 'al',
 'jazeera',
 '.',
 'week',
 'everyone',
 'west',
 'thought',
 'us-led',
 'military',
 'action',
 'syria',
 'fait',
 'accompli',
 '.',
 'thanks',
 'brief',
 'wave',
 'sanity',
 'swept',
 'british',
 'parliament',
 ',',
 'u',
 'could',
 'proceed',
 'forward',
 'without',
 'appearing',
 'hilteresque',
 'themselves',
 '.',
 'despite',
 'hype',
 'mainstream',
 'medium',
 'fake',
 'news',
 ',',
 'washington',
 'london',
 'official',
 'conspiracy',
 'theory',
 'assad',
 'crossed',
 'red',
 'line',
 'using',
 'sarin',
 'gas',
 'people',
 '.',
 'timely',
 'analysis',
 ',',
 'one',
 'wider',
 'geopolitical',
 'scope',
 ',',
 'delivered',
 'aaron',
 'hawkins',
 'founder',
 'storm',
 'cloud',
 'gathering',
 '.',
 'watch',
 ':',
 'support',
 'wire',
 'subscribe',
 '&',
 'become',
 'member',
 '@',
 'wire.tv']

In [17]:
# tokens (list of words) ko wapas ek single string mein jodna
df["clean_text"] = df["tokens"].apply(lambda x: " ".join(x))

df["clean_text"].iloc[0]

'st century wire say back august , united nation investigator led carla del ponte found evidence alleged chemical weapon attack syrian military actually staged u , saudi qatari-backed jihadist rebel . definition , false flag attack . regardless fact , western medium political leader still decided blame damascus incident . object game simple : engineer virtual violation obama famous red line , providing legal pretext , however spurious , use western military force nation state syria guise great st century western military intervention tactic known responsibility protect ( rp ) . video uploaded storm cloud gathering sept , , demonstrated entire mainstream medium going one way pushing fraudulent event purpose generating new war alternative medium outlet reporting truth . history side alternative medium , like cnn , abc , nbc , bbc al jazeera . week everyone west thought us-led military action syria fait accompli . thanks brief wave sanity swept british parliament , u could proceed forward without appearing hilteresque themselves . despite hype mainstream medium fake news , washington london official conspiracy theory assad crossed red line using sarin gas people . timely analysis , one wider geopolitical scope , delivered aaron hawkins founder storm cloud gathering . watch : support wire subscribe & become member @ wire.tv'

In [18]:
df["clean_text"].iloc[0]

'st century wire say back august , united nation investigator led carla del ponte found evidence alleged chemical weapon attack syrian military actually staged u , saudi qatari-backed jihadist rebel . definition , false flag attack . regardless fact , western medium political leader still decided blame damascus incident . object game simple : engineer virtual violation obama famous red line , providing legal pretext , however spurious , use western military force nation state syria guise great st century western military intervention tactic known responsibility protect ( rp ) . video uploaded storm cloud gathering sept , , demonstrated entire mainstream medium going one way pushing fraudulent event purpose generating new war alternative medium outlet reporting truth . history side alternative medium , like cnn , abc , nbc , bbc al jazeera . week everyone west thought us-led military action syria fait accompli . thanks brief wave sanity swept british parliament , u could proceed forward without appearing hilteresque themselves . despite hype mainstream medium fake news , washington london official conspiracy theory assad crossed red line using sarin gas people . timely analysis , one wider geopolitical scope , delivered aaron hawkins founder storm cloud gathering . watch : support wire subscribe & become member @ wire.tv'

In [1]:
import pandas as pd
import re
import string
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

nltk.download('stopwords')
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('wordnet')

# Step 1: Load data
fake_df = pd.read_csv("Fake.csv")
real_df = pd.read_csv("True.csv")

# Step 2: Label
fake_df["label"] = 0
real_df["label"] = 1

# Step 3: Merge + Shuffle
df = pd.concat([fake_df, real_df], axis=0)
df = df.sample(frac=1).reset_index(drop=True)

# Step 4: Remove duplicates
df.drop_duplicates(inplace=True)

# Step 5: Lowercase
df["text"] = df["text"].str.lower()

# Step 6: Remove URLs
def remove_urls(text):
    return re.sub(r"http\S+|www\S+", "", text)
df["text"] = df["text"].apply(remove_urls)

# Step 7: Remove HTML tags
def remove_html_tags(text):
    return re.sub(r"<.*?>", "", text)
df["text"] = df["text"].apply(remove_html_tags)

# Step 8: Remove punctuation (fixed version - removes ANY non-letter/number/space character)
def remove_punctuation(text):
    text = re.sub(r'[^a-z0-9\s]', ' ', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text
df["text"] = df["text"].apply(remove_punctuation)

# Step 9: Remove numbers
def remove_numbers(text):
    return re.sub(r"\d+", "", text)
df["text"] = df["text"].apply(remove_numbers)

# Step 10: Remove stopwords
stop_words = set(stopwords.words('english'))
def remove_stopwords(text):
    words = text.split()
    filtered_words = [word for word in words if word not in stop_words]
    return " ".join(filtered_words)
df["text"] = df["text"].apply(remove_stopwords)

# Step 11: Tokenization
def tokenize_text(text):
    return word_tokenize(text)
df["tokens"] = df["text"].apply(tokenize_text)

# Step 12: Lemmatization
lemmatizer = WordNetLemmatizer()
def lemmatize_tokens(tokens):
    return [lemmatizer.lemmatize(word) for word in tokens]
df["tokens"] = df["tokens"].apply(lemmatize_tokens)

# Step 13: Join tokens back into clean sentence
df["clean_text"] = df["tokens"].apply(lambda x: " ".join(x))

print("Done! Shape:", df.shape)
df["clean_text"].iloc[0]

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

Done! Shape: (44689, 7)

'beirut reuters lebanese president michel aoun office said saturday saad al hariri phoned outside lebanon resign country prime minister aoun awaited hariri return hear circumstance resignation'

In [3]:
df.to_csv("cleaned_news_data.csv", index=False)